interconnect: fix build error without DEBUGFS
The previous fix was incorrect, and now we get a build failure
without CONFIG_DEBUG_FS:

drivers/interconnect/core.c: In function 'icc_init':
drivers/interconnect/core.c:710:32: error: 'icc_summary_fops' undeclared (first use in this function)

Removing the last #ifdef as well makes it all work as intended.

Fixes: 8f023d0cb757 ("interconnect: core: Fix unused variable compiler warning")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Georgi Djakov <georgi.djakov@linaro.org>